---
controller_groups:
  - name: azure_vms
    inventory: "{{ demo_azure_inventory_name }}"
    hosts:
      - "{{ azure_vm_hostname }}"

  - name: aws_vms
    inventory: "{{ demo_aws_inventory_name }}"
    hosts:
      - "{{ aws_ec2_hostname }}"
