---
controller_groups:
  - name: azure_vms
    inventory: Azure-Resources
    hosts:
      - "{{ azure_vm_hostname }}"

  - name: aws_vms
    inventory: AWS-Resources
    hosts:
      - "{{ aws_ec2_hostname }}"
